# Contributions

The following people contributed to the brainstorming document:

- Lisa DeBruine (lisa.debruine@glasgow.ac.uk) - rstats, web coding (js, php), very little python (not averse, just don’t have time to fall down that rabbit hole), psychology, big team science, open science, advising the APA editors on open code
- Courtney Hilton (courtneyhilton@g.harvard.edu) - rstats, web coding (js, jsPsych, React, html/css, etc), a little python, a little matlab, psychology of music/language, online citizen science methods
- Steven Weisberg (stevenweisberg@ufl.edu) - python (Psychopy, scipy, pandas, etc.), Unity3d, some rstats and Matlab, some bash, fMRI (nipype, FSL), psychology, neuroscience, spatial navigation, virtual reality
- Kaija Gahm (kgahm@ucla.edu) - rstats, a tiny bit of matlab and python. Carpentries instructor. Open science (on the board for SORTEE, an open/reproducible science society for ecology/evolution). Research interests in behavioral ecology, movement ecology, animal behavior.
- Emily Kothe (emily.kothe@deakin.edu.au) - rstats, web coding (php, html/css), some scripting in Inquisit/ePrime etc, health/environmental/social psychology. 
- Edward Ivimey-Cook (e.ivimeycook@gmail.com) - rstats. Chair of SORTEE conference. Research interests in ageing.
- Eirini Zormpa (ezormpa@turing.ac.uk) - rstats, psychology, linguistics, open science, reproducibility
- Damie Pak (dp495@cornell.edu) - rstats, theoretical ecology (mathematical modeling and data analysis in pest and disease systems)
- Alexandre Courtiol (alexandre.courtiol@gmail.com) - rstats, rare usage of "C, C++, Python, Java, Delphi", stats analyses, agent based model, modeling, evolution/ecology/demography, animal behaviour, human evolution, wildlife conservation.
- Hao Ye (haoye@ufl.edu) - rstats (in a past life: matlab, C++, lisp/scheme), open science & reproducibility, editor @ Methods in Ecology & Evolution, reviewer @ JOSS
- Martina Sladekova (m.sladekova@sussex.ac.uk) - rstats and some python; psychology, meta-science, quantitative methods, reproducibility.
- Ekaterina Pronizius (ekaterina.pronizius@univiea.ac.at) - rstats, matlab, spm12, SPSS, neuro-psychology, big team science, meta-science, open science, reproducibility. 
- Lisa Levinson (lisalev@umich.edu) - rstats, linguistics, psycholinguistics, web-based reaction time research, undergraduate research mentorship and training, a little bit of computational linguistics/language model work and collaborating with python-focused folks (mostly a python “reader”). Very interested in open science, replication, and reproducibility but early in my journey.
- Jacek Buczny (jbuczny@gmail.com) - R, meta-analysis, multilevel, open science, team science, associate editor who wants to promote code/data sharing, personality psychology, teaching stats/methods
- Mahmoud Elsherif (elsherim@bham.ac.uk) - Research Interests: Language processing, neurodiversity and joint attention; open scholarship and meta science, reproducibility; rstats- can help with Rmarkdown section
- Clare Conry-Murray (cconrymu@sju.edu)- Rstats beginner, Research interested: moral development, Reasoning about gender and culture, research methods.
- David Moreau (d.moreau@auckland.ac.nz) - rstats, methods, open science, meta-analysis, reproducibility, neuroscience, psychology. 
- Bradley J. Baker (bradley.baker@temple.edu) - R, some Python; long disused background in computer science (C, PERL). Research interest in sport consumer behavior with secondary area in research methods and metascience.
- Andrew Stewart (andrew.stewart@manchester.ac.uk) - mostly R, some Python, a little bash. Big fan of Docker/Binder to capture the computational environment (system level as well as R/Python versions and package versions) - also Clean Code principles, Psychology, Open and Reproducible Research, topic editor @ JOSS
- Dylan Gomes (Dylan.GE.Gomes@gmail.com) - lots of R/Rmd, regular git/GitHub user, some matlab, a little python. Open science advocate (two SORTEE, see above, committees). Quantitative ecologist. 
- Utek (utek@outlook.com) - Amateur R user, trying to integrate more Rmd into my workflow, and recent git CLI convert. Research interests: personality, psychopathology, and treatment adherence. Hope I will contribute something meaningful and learn something along the way :)
- Gustav Nilsonne (gustav.nilsonne@ki.se) - R, open science, reproducibility, metascience, systematic quality control. Long experience of making errors and trying to detect and mitigate them. Interested in how to structurally integrate error-reducing elements into academic workflows.
- Saeed Shafiei Sabet (saeedfisheries@gmail.com) - Using R for soundscapes visualizations. Research interests: Bioacoustics, sound impacts, antipredator behaviour, swimming activities, stress, animal behaviour, fish, crustaceans.
- Bo Yao (b.yao1@lancaster.ac.uk) - CogNeuro of Language and Psycholinguistics. Using R notebook for data and code sharing for research (tidyverse, lme4, brms). Coding experience includes mainly R and MatLab. Does a little python and java for building online experiments only.
- Gairan Pamei (pamei-gairan@link.cuhk.edu.hk)- R stats beginner (a big time struggler). Research interests: Literacy and Language Development, Research Methods and Metascience  
- Ana Martinovici (martinovici@rsm.nl) - experience with: R, Stan, R Markdown, Bash, Git, Make. I can use python (using Reticulate in RStudio), Matlab, basic JS, and MPlus but at a lower level of proficiency compared to R. I do research on the role of attention in decision making, so I have experience with eye-tracking data and choice modeling. I have experience teaching students how to use version control, R, and collect data via APIs (Twitter). 
- Luiza Andrade (luiza.c.andrade@gmail.com) - rstats, git, Stata, some Python. Development economics, research transparency - have been running reproducibility checks for working papers and organizing code review session for ~5 years
